### ISSUE TITLE
Issue with path separators on Linux

### ISSUE THREAD

**Issue by LemonHeadOnGit** [SpotAlong/SpotAlong-Client#2]
Many lines of code in the program explicitly use `\\` instead of something like `os.path.sep`. This causes many issues on Linux and (most likely) macOS.

I will submit a pull request soon to resolve this! :)

**Comment by CriticalElement** [comment]
Yeah, most of the codebase was written when I had no clue about good code conventions 😄. I was eventually going to do this someday, but I really appreciate it!
