### ISSUE TITLE
Friend requests not working!

### ISSUE THREAD

**Issue by Crimstrix** [SpotAlong/SpotAlong-Client#4]
Me and my friend recently wanted to use this but our friendrequests give an error? Any clue on why?

**Comment by Crimstrix** [comment]
If you want to attempt this yourself, My friend code is 3637-8513-6869

**Comment by CriticalElement** [comment]
This is one of those errors that I thought I fixed several times, but I guess it still occurs. Will update when I find further details.

**Comment by CriticalElement** [comment]
This should be fixed now, with an update I made to the server. I also cleared the list of friend requests.
